[package]
name = "Ludum"
version = "0.1.0-beta"
authors = ["Nathan McMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "libl/",
    "tests/",
    "tools/",
]

[dependencies]
libl = { path = "libl/" }
tools = { path = "tools/" }
